---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jenkins-secret
  namespace: jenkins
spec:
  encryptedData:
    pass: AgAH1byJvVBYdFLy5rk5bdlZkH6ibNCGOCl1QBCrUIvrTQQvnM1RExo8bcQdG9VgAPVce7+0l0d8UoWEuHccTfQYjI5MXMra00qPfcZbZzqRDb9laHxPMu49TyKMCEr50HdXEKB8vIufGT/ZJpnlaDoHoVyQtSRBMfCxq2vK+suN1rp5CYvAdr1nPi8DLO5at1PF+VLNYgAZSSTkHIAuQTRcJxTO2wMYXQS7HWK47nGFBJqPKr2xlVDweiTMKrItHHOwSVQprZl0Rj7bOBOdVyq8ie+3LVHvHhjkItbxTadiDaYGhUDR4sUhwyzgzW7nB5PjxAIAGP23i4dGKNyx1oV7R8UDuzmvXZBKY76Uj5yrMOuk5tvuOPj37CkqfwueddPkSl5mRP+LLTfCG/xQa6AIFHB+VgPkmKCYr0kIr+S9724LeFPmxzx6pYydiHDrP3MO2CVy+LHnYXT7kl7O3CXDsDkPoM/Qz5bkry8UvvYNfPQ4KdQT4PD4ow77SHc3rPbMXk5VqV+SbJdpMC421CrOj4jXKXl9sOqSBED2Mm4tS0exvJHiu+nWQsAPJsTwic2Gf2amTZxNVrKOfaQ2RZ+jwYrpUtobbo9ySC/bSrE64/D9tmpl3Cz8cJ+fUPo5Fi1UV/189GGC1cabb4iDBD4Jrvb/3wSUOe99AkgJJAuFIYZqWuTddCzLXBmWkEwuET+wFPoYxH8=
  template:
    metadata:
      creationTimestamp: null
      name: jenkins-secret
      namespace: jenkins
    type: Opaque
