apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./argo-app-manifest
    repoURL: https://infinity-step.github.io/project_14/
    targetRevision: 1.0.1
  syncPolicy:
    automated: {}
